---
Name: app
---

SilverStripe\Core\Manifest\ModuleManifest:
  project: app

SilverStripe\ORM\Connect\MySQLDatabase:
  connection_charset: utf8mb4
  connection_collation: utf8mb4_unicode_ci
  charset: utf8mb4
  collation: utf8mb4_unicode_ci

Silverstripe\SiteConfig\SiteConfig:
  extensions:
    - App\Extensions\SiteConfigExtension