---
Name: app
---

SilverStripe\Core\Manifest\ModuleManifest:
  project: app

Silverstripe\SiteConfig\SiteConfig:
  extensions:
    - App\Extensions\SiteConfigExtension

SilverStripe\Assets\File:
  allowed_extensions: [svg, js]

SilverStripe\Core\Injector\Injector:
  SilverStripe\View\Requirements_Backend:
    properties:
      forceJSToBottom: true

SilverStripe\i18n\i18n:
  default_locale: 'en_US'

Page:
  extensions:
    - App\Extensions\OpenGraphExtension